spring:
  application:
    name: Backend
  datasource:
    url: jdbc:postgresql://localhost:5432/post_service
    username: post
    password: post
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:data/data.sql
      mode: never
